### ISSUE TITLE
Add API Request Messages

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/ajax-project#15]
## 🕹️ Functionality 

User will see a loading message when the API Request is being made and a maximum message limit when reached.

## ✅  Tasks

- [x] A loading message when the API request is loading.
  - [x] Create a modal for the API Request time.
  - [x] Add a loading animation to the HTML page.
  - [x] Get the modal's ID and change the display accordingly.
- [x] An API request limit.
  - [x] Check when the API request limit has been reached.
  - [x] Create a modal for the API request limit with a close button.
  - [x] Show the modal when the API request limit has been reached.
- [x] An error message if there is no internet connection.
  - [x] Check for the error.
  - [x] Create a modal for the error.
  - [x] Show the modal when there is no connection.
- [x] Fix all bugs and remove unused CSS selectors.
