### ISSUE TITLE
User can see a dropdown list with searchable stock options

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/ajax-project#17]
## 🕹️ Functionality

User can a dropdown list with possible stock options according to what has been typed.

## ✅ Task List

- [ ] Create a function that will listen to the inputs and check for matches in the `stockSymbolName` array.
  - [ ] Use the `$searchInput` to listen for inputs.
  - [ ] Check the inputs for matching values (name or symbol) in the `stockSymbolName` array.
  - [ ] Log to the console the first 5 matching values.
- [ ] Create a function to render the results.
  - [ ] Create a model for the dropdown list in the HTML file.
  - [ ] The elements must be `anchor` tags.
  - [ ] Show the symbol and the name of the stock on each rendered line.
- [ ] Add the function to the submit event listener and return the chosen value.
- [ ] Check the code for unnecessary code.
