### ISSUE TITLE
User can search for a stock

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/ajax-project#2]
## 🕹️ Functionality

User should be able to type a stock ticker symbol in the input box and see the result by pressing the search button.

## ✅ Task List

- [x] Using HTML and CSS, create a simple responsive header with a logo and a navigation bar.
- [x] Pick a color scheme for the project.
- [x] Pick a pair of fonts for the project.
- [x] Create a responsive form element with the search input and the search button.
- [x] Add the font to the form elements.
- [x] Make all form elements required.
- [x] Create event listeners for the focus and blur events on the search input.
- [x] Set the attribute of the input search box to hide the place holder when focus event happens.
- [x] Set the attribute of the input search box to show the place holder when blur event happens.
- [x] Listen for submit events on the form.
- [x] Store the value of the search input in a variable.
- [x] Create a API request for the value in the search input.
- [x] Create an array to save the return information from the API.
- [x] Store the desired properties from the returned request into the array as an object.
- [x] Create a modal informing that the searched symbol does no exist with a close button.
- [x] Add an event listener to the close button.
- [x] The close button should change the style attribute on the `div.modal` to `display:none`.
- [x] If the inputted symbol returns undefined data, change the style attribute on the `div.modal` to `display:flex`.
- [x] If the inputted symbol returns non-undefined data, store the information in the stock array.
- [x] Add a paragraph explaining how the search input works.
- [x] Test all functionality and remove unused CSS Selectors.
