### ISSUE TITLE
User can see stock details

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/ajax-project#3]
## ✅ Task List

- [x] Create an object called `data`.
  - [x] The empty stock array should be one of its proprieties.
  - [x] The second propriety should be `data-view` with an empty string.
- [x] Create a responsive HTML structure for the `data-view="detail"`.
  - [x] Add a save button to the end of the detail-view.
- [x] Add the `data-view` attribute to the necessary HTML elements.
- [x] Create the local storage.
  - [x] Add an event listener to the `window` object for the `beforeunload` event.
  - [x] Stringify the the `data` object and store the value in a variable called `dataJSON`.
  - [x] Using the `setItem( )` method on the `localStorage` object, with `javascript-local-storage` and `dataJSON` as arguments.
  - [x] Outside of the created event listener, using the `getItem( )` method on the `localStorage` object, get the keyName `javascript-local-storage`, and store the returned value to a variable names `previousDataJSON`.
  - [x] Using an `if` statement check if the variable `previousDataJSON` is not `null`.
  - [x] If true, use the `parse` method on the `JSON` object with the `previousDataJSON` as the argument and store the returned value in the `data` object.
- [x] Create a function called `swapView` with `view` as its only argument.
  - [x] Query the DOM for a NodeList with all elements with the `data-view` attribute.
  - [x] Make the `swapView( )` function show the `view` in the argument and hide all others.
  - [x] make the `swapView( )` function write the name of the view it showed to the `data.dataview` object.
- [x] Create a function called `renderDetail`.
  - [x] Create the necessary HTML elements, set the appropriate classes, add text content according to the `stockInfo` object and append them to their respective parent objects.
  - [x] Return the final parent element with all is children appended.
  - [x] Add the `renderDetail` function to the submit event listener function.
- [x] Remove unused CSS selectors and fix all bugs.
