### ISSUE TITLE
User can save their favorite stocks

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/ajax-project#4]
## 🕹️ Functionality

User can click on the `Add to Favorites` button and the current shown stock will be saved to the `data` object.

## ✅ Task List

- [x] `Add to Favorites` button:
  - [x] Add an `ID` attribute to the `a` tag created by the `renderSearchDetail` function.
  - [x] Add a click event listener to the `document` object.
  - [x] If the click event is fired, push the `stockInfo` object in the `data.stocks` array.
- [x] Fix bugs and remove unused CSS selectors.
