### ISSUE TITLE
User can see a list of their favorite stocks

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/ajax-project#5]
## 🕹️ Functionality

By clicking on favorites, the user can see a list of all the stocks he saved.

## ✅ Task List

- [x] In the click event listener for the `document` object check if the clicked `a` element in inside a `nav` element.
- [x] Add the `swapView` function with the argument set to be the value of the `data-view` attribute of the clicked `a` element.
- [x] Create a new `section` element in the HTML file with [data-view="favorites"].
- [x] Create the HTML structure for the `section[data-view="favorites"]`.
- [x] Create a function called `renderFavorites` that returns a `div` element containing the structure of one favorite stock.
- [x] Within the `swapView` function, call the `renderFavorites` function for each item in the `data.stocks` array.
- [x] Test that by going back to the `search` view and adding more stocks, they get added to the `favorite` view list.
- [x] Fix bugs and clean-up the code.
