### ISSUE TITLE
User can remove stocks from their favorite list

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/ajax-project#6]
## 🕹️ Functionality

User can delete a stocks that was added to the Favorite List.

## ✅ Task List

- [x] Add an event listener to the `trash button`.
- [x] If the `trash button` is clicked, check the name of the clicked stock with the index of the `data.stocks.name`.
- [x] Remove the indexed item from the `data.stocks`.
- [x] Call the `renderFavorites` function and append the returned value to the section element with the `[data-view="favorite"]`.
- [x] Add to the `renderFavorites` function to adds text to the `section[data-view="favorite"]` if the `data.stocks` is empty.
- [x] Create a modal to confirm the stock was saved.
  - [x] Create a modal structure in the HTML file.
  - [x] Show the modal once the "Add to favorites" is clicked.
  - [x] Add a timer function to the modal to disappear after 2 seconds.
  - [x] Add the name of the added stock to the added modal.
- [x] Create a modal if the stock has already been added to the `data.stocks`.
- [x] Fix bugs and remove unused CSS Selectors.
